### ISSUE TITLE
Pre-launch checklist and questions

### ISSUE THREAD

**Issue by ajroberts0417** [ajroberts0417/qrono#5]
- [ ] Do we have a backup of the database somewhere in case things go horribly wrong?
- [ ] Do we have snapshots of the database stored so we can restore in case things go horribly wrong?
- [ ] Have we done a security audit?
- [ ] What should we do to complete a security audit?
